FROM alpine:3.4
MAINTAINER shr386.docker@outlook.com

RUN cat /etc/apk/repositories

RUN apk add --no-cache --virtual .build-deps \
 gcc g++ libc-dev make curl wget tar autoconf automake libtool texinfo \
 libevent-dev pcre-dev libssh-dev zlib-dev openssl-dev && \
 apk add --no-cache libevent pcre libssh

RUN apk add --no-cache privoxy
RUN apk add --no-cache tor

###########################################

ADD src/polipo-1.1.1.tar.gz /src/
#RUN ls -R /src

RUN cd /src/polipo-1.1.1 && \
make PREFIX=/opt/proxy \
 LOCAL_ROOT=/opt/proxy/share/polipo/www \
 DISK_CACHE_ROOT=/opt/proxy/var/log/polipo/cache \
 all install

###########################################

RUN apk del .build-deps && rm -fvr /src

RUN mkdir -p /tmp/privoxy-config
COPY src/privoxy-config/* /tmp/privoxy-config/
COPY adblock.action /tmp/privoxy-config/

###ADD https://github.com/Yelp/dumb-init/releases/download/v1.0.1/dumb-init_1.0.1_amd64 /dumb-init

COPY dumb-init_1.0.1_amd64 /dumb-init
COPY start.sh /

RUN ( echo '#!/bin/sh'; echo 'tee -a /opt/proxy/etc/privoxy/config' ) > /add-rules.sh
RUN chmod +x /dumb-init /start.sh /add-rules.sh

# polipo 8123, privoxy 8118, ratproxy 5555, tor 9050
EXPOSE 8123
EXPOSE 8118
# EXPOSE 5555
EXPOSE 9050

# log, cache, etc
VOLUME [ "/opt/proxy/var","/opt/proxy/etc" ]

WORKDIR /opt/proxy/bin

CMD [ "/dumb-init", "/start.sh" ]
